input([4,6,'b','bbbdbtbbbj']).
input([1,6,'g','ggvggbgggstg']).
input([1,4,'s','lssss']).
input([13,14,'v','hvvcvvvvvvvvvsvvv']).
input([3,5,'m','lcmmm']).
input([3,4,'t','stht']).
input([5,6,'b','dbkbhb']).
input([4,7,'p','ppfppppq']).
input([4,5,'j','jjjjj']).
input([3,12,'s','sskssssssssss']).
input([14,15,'z','zrndzbmrzzpzzqzj']).
input([12,18,'l','tllllllllllllplllbl']).
input([8,10,'b','bdbvqbtbrb']).
input([1,3,'c','tcqccc']).
input([1,2,'n','nbnj']).
input([5,7,'c','ccccccccc']).
input([9,10,'l','hpmslrlgll']).
input([6,9,'n','nnnnnnnnb']).
input([6,10,'r','rmzjlrsxkbw']).
input([6,8,'r','bzqnnrrrj']).
input([4,14,'c','mfffvcbtchzrqcn']).
input([1,6,'f','ffffffffffffff']).
input([2,5,'f','wxtkf']).
input([8,12,'b','rdcbbjbzbbpb']).
input([8,18,'d','ddtdddddddwvdfdsdd']).
input([5,8,'s','sssmsgpgszms']).
input([6,11,'x','xxxxxvxxxxxt']).
input([17,18,'n','jhrnnzpxzngfqrntmnc']).
input([13,14,'r','rrrmrrrrlrrshvrrr']).
input([4,5,'h','hhhhrhh']).
input([8,10,'d','dgwtdsxnncd']).
input([9,13,'q','qqbpqmqgmqwqbqqqxcgq']).
input([2,5,'g','gjjcpgg']).
input([6,12,'t','ttttvttttttrtt']).
input([3,9,'h','hhhhhhhhsh']).
input([15,16,'p','ppppsppppppppppz']).
input([2,5,'c','csccctcccc']).
input([11,14,'p','pppppppppppppnp']).
input([8,9,'j','jvbjjjjrjbjj']).
input([8,16,'b','qklbmbntmvbhxplbbcb']).
input([12,13,'j','jjjjsjmfjjjkhj']).
input([2,13,'t','llckxhfmtznptndcsx']).
input([6,8,'x','dxxxxvxxtt']).
input([3,4,'d','ddht']).
input([3,4,'t','ttdtt']).
input([11,12,'r','rrrrrrrrrrrd']).
input([9,10,'h','hhhhhhhhgh']).
input([3,16,'h','hhhhhhhhhhhhhhnhhh']).
input([10,11,'h','hxhhhdhhhsh']).
input([1,7,'n','jnfnjnn']).
input([3,4,'m','msmnpmpf']).
input([15,17,'t','tpdtttgltvtttztlv']).
input([7,10,'v','vvpsvpgjzvvvvjs']).
input([1,5,'p','pxppg']).
input([2,7,'w','jwhgkgvxcv']).
input([13,14,'m','pxxmjznmrzdsbbmmfj']).
input([1,4,'d','ddddd']).
input([14,16,'r','rrrrrrrrrrrrrwrr']).
input([2,5,'l','klbtzzlrlslgswhljtq']).
input([6,12,'c','qccrcpccccccdccccc']).
input([2,18,'l','llllllllvllllllllkll']).
input([18,20,'z','zzzzzzzzszqzwzrzzzzn']).
input([5,16,'c','cbccclcfcncvqztqc']).
input([7,11,'m','fnwmtsmgpxncnr']).
input([6,7,'h','hpjrhbhkshnchbhpph']).
input([11,12,'s','ssssssssssps']).
input([6,9,'s','jfsmmssssqz']).
input([1,15,'l','llllllllllllllbll']).
input([2,6,'g','gggggwgggpggggggg']).
input([6,9,'j','jjjpjjjjn']).
input([9,13,'n','nnnnnnnnnnnnnn']).
input([10,13,'t','cgntllxnvpkjwxtght']).
input([2,11,'f','xcftbcdcndkgm']).
input([10,13,'j','jjjjjjjjjjjjvj']).
input([9,17,'f','rfrffnsffxqflbffvv']).
input([6,11,'k','kkkkkrwkqckmk']).
input([5,7,'q','zfqqqqqn']).
input([12,13,'c','cfcccvccccckccccv']).
input([5,15,'z','xhzzzzzzzzfzzknzz']).
input([18,19,'f','jkfksvmfjbdffffffff']).
input([8,11,'h','hhhhmhhkhsfdg']).
input([14,16,'s','ssssssdjssssssssssss']).
input([15,16,'t','jtmjhsxqqmmthmtttm']).
input([5,7,'h','hkbjhjhh']).
input([2,6,'n','knprnfnfhhrcnk']).
input([3,4,'w','snwd']).
input([5,11,'w','wwwwnwwwwwwwwwwww']).
input([2,12,'k','bkqjghpktfsk']).
input([14,15,'v','vvvsvvvvvvvvvxv']).
input([8,9,'w','fxwwwwwscwl']).
input([9,15,'c','sbjvvsmdvqknbccxxx']).
input([6,15,'t','tpwjtdnnldthxvn']).
input([13,15,'t','tttttrzmzttjttt']).
input([3,11,'m','mmvmlmmmwfmjx']).
input([13,14,'s','gskssssssscssssqjssl']).
input([5,10,'l','bfnmqlldllp']).
input([17,18,'q','qkwqqqqqqqqqqqrqqqqq']).
input([2,5,'r','rsvrrq']).
input([3,4,'j','jjjdj']).
input([3,4,'m','mtmk']).
input([8,9,'k','vsvkvkrkc']).
input([10,12,'t','ttttttcttttgttt']).
input([3,4,'n','trzw']).
input([5,11,'q','qqmpsqbxkqq']).
input([13,15,'s','sqsssnmwqszfsmv']).
input([5,6,'b','bbbbzvb']).
input([5,13,'p','pjjhpnqpzpmpfpfp']).
input([4,5,'l','mgnwlrw']).
input([1,7,'k','fkzxwkj']).
input([1,10,'q','qgxqqqqqqg']).
input([8,9,'s','ssqssssfss']).
input([7,8,'c','xxcscclccdvcmqcc']).
input([2,6,'d','xdlmzdzxrpmlnt']).
input([3,9,'s','sssssnssgbs']).
input([7,10,'h','sblrrhqrhh']).
input([3,5,'n','xnndnnnfnw']).
input([9,10,'l','vllllqlllhllljxlp']).
input([2,5,'d','ddxzbxk']).
input([10,14,'m','mmmmmmmmmmdmmmmsmmm']).
input([1,2,'f','ffffw']).
input([14,15,'g','wdjhplhrbcxdgpnt']).
input([1,2,'l','klllllll']).
input([10,11,'k','ckkhkkvkkkmkkjkwkkwk']).
input([7,9,'f','ffrhdvftfpjfqffhnfsf']).
input([4,5,'c','kkjksrmkccg']).
input([5,9,'r','rrrrhrrrrr']).
input([5,6,'p','pppppth']).
input([4,10,'t','kpfwzjtchtbndblrvst']).
input([1,5,'l','mllllllnllll']).
input([13,16,'r','rrrvrrrrrrrrzrrg']).
input([17,18,'x','xxfxxxxxxxxsxxxxxsxx']).
input([8,11,'w','rwbnqrngcvpgwwww']).
input([4,8,'z','zzzzzzzzzz']).
input([4,9,'b','bbvvbbbbr']).
input([2,5,'x','qlfhxkx']).
input([3,8,'t','wvptttttttt']).
input([1,3,'m','hmmmmqmm']).
input([17,19,'h','nhhhdvhnhrhhhhnhmdh']).
input([11,12,'s','psszbdpsgfks']).
input([6,7,'s','sssssshs']).
input([10,15,'l','mnkdvnvmxljjtggwcl']).
input([1,13,'j','qjjjjjjjjjjjdj']).
input([4,9,'l','jxvkwhlmlhdtgwvgsdzz']).
input([5,9,'c','ccfghhccccgc']).
input([10,11,'v','vvvvvvvvvvv']).
input([7,8,'t','cntwzshkzvmrnnkr']).
input([1,11,'l','tllllllltllll']).
input([15,17,'l','lllglvctrvllzkllt']).
input([3,5,'n','ncnnp']).
input([2,3,'q','jsqqh']).
input([4,10,'h','hhhhhhhhhvh']).
input([16,18,'b','bbnbbbbbtbbkktbbzdr']).
input([4,6,'g','kbggdhgggggggggggfc']).
input([12,13,'p','cpvcppqpplwpt']).
input([5,10,'h','fvhhbrhpghchhhhhh']).
input([2,5,'b','bbvzn']).
input([14,15,'x','xxxbxnwxxxxzxxh']).
input([13,15,'n','nnfgdglfnntnjqn']).
input([2,4,'c','cfccc']).
input([3,5,'v','vrvvzdvv']).
input([17,19,'v','vvvvvvvvvvvvvvvvvvsv']).
input([1,20,'h','hhhhhhhhhhqhhhhhhhhh']).
input([4,15,'q','qqqtqqqqqqqqqqqqlq']).
input([11,13,'h','hhkhvhhhhwhgk']).
input([8,11,'p','ppvppppppptspf']).
input([8,9,'m','mmmpmmkmdmpkspmg']).
input([1,7,'m','lcmvggm']).
input([6,12,'v','tvfstvvpvzsvcv']).
input([8,9,'n','nnnqnnwrrdzlmnwlznrn']).
input([1,5,'s','msssms']).
input([1,3,'v','vpdzvdvgv']).
input([6,9,'g','drgrfggcg']).
input([6,16,'x','djpxhxvncxfghsxx']).
input([1,3,'b','sjbwwxbvtvbkt']).
input([6,8,'c','cccccstccjhv']).
input([1,11,'q','qqqpqqqqqqwqqq']).
input([9,11,'m','vsbmmmmmmmqmmsm']).
input([2,7,'g','gqggggggg']).
input([2,3,'m','mrgvm']).
input([6,7,'c','cccpcfcc']).
input([6,10,'w','swbngwswnxnww']).
input([13,14,'r','rrrrrrrrrrwrrgrdr']).
input([3,9,'v','vctxhxtfvq']).
input([2,9,'r','jrrcslgplcprlvgthg']).
input([2,3,'n','hnnnsxclvdj']).
input([10,11,'h','zrhghhqhgzh']).
input([15,18,'z','zzzlzzzzzzzzpzqzpzzz']).
input([3,8,'f','fffffrfl']).
input([1,4,'l','rllllfl']).
input([1,2,'n','nnnnnvtnv']).
input([17,19,'z','zzzzzzzzzzzzzzzzzzqz']).
input([13,15,'n','nnnznnnnnnznnnn']).
input([2,5,'c','gcccncjmsncfcntjc']).
input([8,9,'h','hhhhhhhhbpsfh']).
input([7,11,'r','lzvvlbrgjgrr']).
input([5,11,'x','xxxxqxxxxxxx']).
input([4,7,'p','gqpkmppzpsmtzhfdfpl']).
input([3,4,'j','jjdjdg']).
input([14,16,'z','zzzzzzzgjzzzzpzf']).
input([1,2,'n','nnnvnwnnnnh']).
input([4,5,'z','jhzzz']).
input([5,7,'k','kkkkkkf']).
input([8,18,'z','khzzrzjzmzzvzzpcclm']).
input([5,10,'m','kjrhwkhmsm']).
input([10,16,'v','vvvvvvvvvvvvvvvwv']).
input([9,10,'l','xhvjsmllkcdtldfxlw']).
input([8,10,'p','ppjvppbpqhpwhppgbp']).
input([4,6,'m','jlmkhm']).
input([1,3,'k','gvpklkkkk']).
input([15,16,'g','ggjggggvgmgtpgcg']).
input([1,4,'j','jbjwj']).
input([1,3,'x','xxxpxxdxxhfx']).
input([14,16,'v','vxmhhdvvfjjqwhtv']).
input([6,7,'l','lnkchzlwxlp']).
input([3,4,'v','vvvcv']).
input([13,14,'p','pbqpppppzbmppc']).
input([6,12,'p','glqwzprpqbqf']).
input([6,12,'l','lllllglllllll']).
input([8,9,'n','nnsnnnndcn']).
input([6,8,'p','prwppppp']).
input([1,10,'q','dqqqqqqqqjq']).
input([12,16,'w','kwtbdnjqmwwxhwcwswkl']).
input([11,14,'r','rrnjghfrrrshlrq']).
input([2,14,'w','vwbbvcvgnxdmxl']).
input([7,8,'g','sqmggkgslkwlvggg']).
input([1,6,'q','tqqqqqq']).
input([2,3,'b','bbbr']).
input([7,9,'b','jnwbswfpbn']).
input([4,5,'n','nnlct']).
input([3,11,'s','ssssssssssp']).
input([2,6,'f','wjlpwf']).
input([5,10,'g','gggghqgqgb']).
input([1,3,'p','ppdg']).
input([4,7,'j','pjnkjjljjj']).
input([1,2,'v','ghmjzxmtxjxnv']).
input([6,14,'k','klgdzfmgdwhqdkhcnzm']).
input([6,11,'z','tgzpzzzzztc']).
input([2,12,'b','cxsmjbdgdnrb']).
input([4,6,'v','lxdvvh']).
input([3,8,'l','pnpdnrll']).
input([7,8,'m','mzmswvmmbxmzlmwhdvq']).
input([13,14,'s','khzssssssssszsssss']).
input([10,18,'d','dmfdlgcxdbzznbrlqn']).
input([13,14,'j','jjjjjjjjjjjjdpjj']).
input([15,17,'j','jjjjjjjjjwjsqjwjj']).
input([10,15,'x','xxfxkzxxhxxxxxvxxw']).
input([7,14,'c','wcccwcmmcccccxhcccc']).
input([2,7,'z','zmzvfzlszr']).
input([7,8,'k','jjkrklrkkv']).
input([8,9,'r','rrrrrjrtz']).
input([2,3,'w','tvws']).
input([1,5,'b','bbbjm']).
input([1,2,'q','tqqjf']).
input([5,10,'j','wlgjghjhjljwtpcdkqwk']).
input([2,5,'c','dzpkc']).
input([5,6,'m','mbvmkm']).
input([4,15,'k','stjkjvvxrmwdpkwsjqvc']).
input([6,9,'h','hwkgjplmhxwgvnbhwh']).
input([12,13,'z','zzzzzzzzzzzzz']).
input([7,8,'q','qqqqqqqqq']).
input([2,5,'c','clcwmccczclcccc']).
input([2,5,'l','jlcgfbflklvpfqxtwgg']).
input([5,7,'n','nnnnnnvnnnnnn']).
input([3,5,'f','gfktfffqvgltsbff']).
input([10,16,'p','jppbttppzpqppppp']).
input([2,3,'m','zmdm']).
input([4,6,'j','zsmtjjdnrpp']).
input([17,18,'j','hvvmrkfnnkvrjtjhjj']).
input([12,15,'d','dtddddddddtwxgld']).
input([8,12,'r','rdzrwfgrmxwttknxz']).
input([6,7,'s','rssbktxsgd']).
input([11,13,'d','ddddmwddddxddndc']).
input([3,6,'p','ppcpspfp']).
input([12,15,'j','jjjjjjgjjjjcjlzj']).
input([8,12,'v','tgjkwfbsxzzvvpmfs']).
input([6,7,'z','trbfbdz']).
input([4,6,'v','vvvvvpvv']).
input([8,16,'p','pnvppdpjppppppph']).
input([8,9,'z','lzzzzpdzk']).
input([1,4,'t','qttzz']).
input([2,3,'d','dhdd']).
input([5,8,'m','mmmkmmxmkj']).
input([2,12,'f','hfhzkwdmrlqvfkn']).
input([5,6,'h','hhhhhph']).
input([14,15,'b','bbbbxbbbbbbbbbh']).
input([2,3,'v','vvcj']).
input([12,19,'d','ddvdwwqdddcdtdmwdqp']).
input([3,4,'s','ssjssssssss']).
input([2,6,'c','wzzxqcdcnlgcph']).
input([11,12,'j','jjdrcjzjkjcs']).
input([4,9,'z','bzzzzzzxzz']).
input([2,8,'b','gjbfkxhb']).
input([1,3,'c','cpksst']).
input([1,5,'h','hhjhh']).
input([14,15,'j','jjjjjjjjjjjjjjr']).
input([8,9,'n','pcndxcfknfbnnls']).
input([10,13,'k','kkkqzkwbkkkrtn']).
input([4,5,'r','rzrrrnrj']).
input([13,15,'p','ppppppppppppppt']).
input([3,6,'j','fjqqzzzjm']).
input([2,9,'m','zmjhctkmf']).
input([5,6,'s','ssmjss']).
input([3,4,'c','jlfd']).
input([8,12,'d','qbddfhnddzgvddddd']).
input([6,7,'p','xfppppcppppxgp']).
input([8,13,'s','sssssssfssssssss']).
input([13,17,'g','xskktsjxlvgfxtzzgfj']).
input([2,4,'q','qqtwfqqnkvbvbhzs']).
input([1,5,'j','cjmjs']).
input([4,5,'c','tvccnc']).
input([3,14,'m','kkfhmnkkmztxtmn']).
input([11,15,'x','xxxxxpxmxxvbxxxvx']).
input([9,11,'l','nhgzwmmrkqhblnk']).
input([7,10,'x','xxxxxdmxxxxxxxx']).
input([13,14,'v','vvvvvvpvvvjvvcvv']).
input([16,17,'n','nnnnqnnbnnnnnnnpn']).
input([3,4,'j','jvjj']).
input([15,16,'q','zlqsgvpztknqjqqwqvf']).
input([3,4,'s','sssrsssdss']).
input([11,13,'g','ggqggmggswggdk']).
input([1,4,'t','jmtzttztqt']).
input([2,3,'v','vvvv']).
input([11,13,'g','cgjgxgggkgbggxg']).
input([4,6,'g','ggggqlhgmz']).
input([8,15,'g','prvxwzkvdhgkjlg']).
input([6,9,'g','gggggnsjlg']).
input([12,14,'p','mmvlpzkmpgtpvj']).
input([7,10,'k','kkkxkkjkkkdkkkp']).
input([14,16,'b','zmztqsrgvjjmswzkbnk']).
input([1,2,'x','xxbxxxxhx']).
input([2,5,'l','tlhsx']).
input([3,5,'x','xxxxn']).
input([4,12,'c','vdnmtmqwnxkcldc']).
input([4,8,'x','xxxxjglx']).
input([5,13,'s','vsssspszssssnsss']).
input([3,6,'k','kkhkkkknb']).
input([3,5,'t','pttqtwnprt']).
input([10,14,'m','ttjqvzmgmmjqzkd']).
input([1,5,'b','bbbbpbbb']).
input([10,15,'d','wdjrhvfngdtlkdl']).
input([6,7,'w','trxwdwww']).
input([2,4,'n','snxqlgtsmdnnjgwrgmms']).
input([16,18,'l','klslpljllqlcslqqll']).
input([4,7,'t','tttwzttjt']).
input([9,10,'f','ffffffffwf']).
input([8,15,'h','trhgxjchhxvvhqp']).
input([8,12,'w','wwwwwwwqwwwg']).
input([12,13,'x','xxxxxxxxsffqlxx']).
input([5,7,'k','kkkklkkkktkk']).
input([1,7,'m','wkmmqmmhf']).
input([12,13,'h','mhhchwhhhzhhcvh']).
input([7,11,'k','kkkkkkwkkkgkk']).
input([4,6,'l','hdlbll']).
input([8,12,'v','fvvvvvvvrvvv']).
input([2,9,'h','hzhhhhhhhhhhhhr']).
input([6,8,'b','qbqjpbbbdsshv']).
input([2,3,'h','hwhl']).
input([4,7,'l','mdllxjgdw']).
input([3,9,'f','rwffzfkpwbzp']).
input([3,5,'t','ttnttt']).
input([7,10,'c','mpcccpndqc']).
input([6,7,'h','fhhhljh']).
input([2,7,'v','pnvzcns']).
input([1,3,'v','vvgv']).
input([5,9,'s','ssssshsspsssssss']).
input([4,6,'j','mjjjjq']).
input([5,14,'h','hwbqghmvmmnvhhrqmj']).
input([5,6,'s','wctjsh']).
input([7,8,'s','sssscsjs']).
input([14,17,'v','vvvvvvvvvvvvvvvvv']).
input([14,15,'w','wxwwwwwwfwwwwsw']).
input([6,7,'v','ksvvvlpvv']).
input([7,18,'s','cssstsvsscshsstsss']).
input([5,6,'b','zzwbpm']).
input([6,7,'r','bvtmpkxspskr']).
input([6,7,'v','lvxrvqv']).
input([15,17,'c','ccccccccccccccccccc']).
input([8,12,'r','ghxpwhxcqjrr']).
input([6,10,'k','kzbcdkndqm']).
input([5,6,'s','tpsxss']).
input([1,5,'p','qlrlp']).
input([4,8,'q','qqqkqqqz']).
input([7,11,'v','vgvsxvwvlxv']).
input([2,5,'b','bgkbb']).
input([3,18,'j','jjsplxjxgqjfjrjxjjlx']).
input([6,10,'k','kxkhkkjkkrvkkk']).
input([7,16,'t','ttttttzttttttttbtttt']).
input([1,7,'l','ptzptslrjgwlfgwq']).
input([8,10,'v','vvqvvvvvvvv']).
input([3,5,'z','zzzhz']).
input([6,7,'c','cbrctgc']).
input([5,16,'l','llllxlllllllllllll']).
input([6,7,'c','chxclqcdrh']).
input([1,10,'c','jcmcccccwcccccjbvc']).
input([8,14,'h','zhhvhhhhhhhhhv']).
input([4,7,'n','rnnnnnfnnnnnvn']).
input([10,12,'w','wwwwwwwsgtwww']).
input([5,8,'c','cmbcctzcj']).
input([5,7,'f','fffskrf']).
input([5,6,'l','lllmzl']).
input([7,14,'m','mmmmmmmmmmmmmmmmmmm']).
input([1,9,'f','jfffffffzvffff']).
input([2,5,'g','ggmng']).
input([16,17,'x','xxxxxxxxxxxxxxxlx']).
input([4,10,'n','npkgjcfnnnnn']).
input([1,13,'d','bhkjgsnzxkdgwbdv']).
input([6,7,'f','ncqfzff']).
input([7,10,'h','hqhhhhhjhhh']).
input([2,4,'v','vnvvv']).
input([1,6,'w','thlmdwgwgtswvtx']).
input([3,7,'d','ddlkhvfdnpbdr']).
input([1,4,'q','qbfq']).
input([2,6,'f','rzfmfrjgcfjk']).
input([10,16,'b','bbbbblbbbkbbbbbbwqb']).
input([13,14,'j','jjhcjnkgvrnwjp']).
input([5,12,'l','lgqwvrlwcllllv']).
input([4,8,'j','jjgpdjssspjfdbt']).
input([1,9,'h','hhhhhhhhwhhh']).
input([4,6,'p','psmppt']).
input([2,3,'h','zhhhk']).
input([2,6,'b','bbbbbmbbvb']).
input([7,9,'z','zzzzzzgzdzz']).
input([8,9,'d','ddgdmdwddd']).
input([2,6,'s','nssssv']).
input([18,20,'x','xxxxxxxxxxxxxxxxxvxx']).
input([9,10,'m','dzckmrbhcmwvkcxmlx']).
input([10,11,'v','vwvvvvwvvghvn']).
input([3,6,'d','wcwxddjhnljfntj']).
input([13,15,'v','vvvvvvvvvvvvcvc']).
input([1,5,'x','xxfxfxxkx']).
input([7,8,'w','wqzjzwwwtw']).
input([2,4,'f','flgl']).
input([3,6,'n','ncfngngdnm']).
input([5,7,'k','kdkmbkkkkxk']).
input([5,6,'x','xxvxth']).
input([5,6,'r','rrhhzr']).
input([4,6,'b','bbbrbbbbbmb']).
input([12,13,'q','qqqqqqqqqzqkqp']).
input([6,14,'n','mlbflnrbhlhpdrfln']).
input([9,12,'q','qqqqqqqqqqqwq']).
input([3,4,'k','rkncnbk']).
input([1,3,'j','jjpj']).
input([8,9,'v','vjvczrvvm']).
input([9,16,'m','tmnmmmxmbmmmrtmmr']).
input([9,11,'q','qqqqqzqqsjxq']).
input([3,5,'h','hhhhcs']).
input([11,12,'k','kkkkkkkkkkkvqk']).
input([11,12,'x','xlxxxjjxxxpx']).
input([1,12,'n','nngtnhlnjfnf']).
input([5,7,'p','ppptppppp']).
input([13,14,'l','lllmlflllhllpm']).
input([13,14,'m','vdkmrdfzmkknmp']).
input([13,15,'s','ssssssqssssscssss']).
input([5,11,'h','hhhlxhhhhhhshh']).
input([10,11,'s','ssssssssssgsssss']).
input([6,7,'q','kqqqqmqnqq']).
input([8,13,'l','llllllltlllljll']).
input([9,12,'j','jjjjjjjjjjjlj']).
input([7,11,'s','gstcncsssscssssss']).
input([4,6,'x','lrtjfnhmpmxj']).
input([9,20,'c','cttccccccnccclcccccc']).
input([1,8,'w','cwwwwwwwwww']).
input([12,13,'n','nnnnnnnngnnnnn']).
input([1,5,'p','pfqwcpnppppwwpqppp']).
input([7,8,'g','gggsgglghg']).
input([6,7,'g','gggggggg']).
input([4,10,'s','ssssssssssss']).
input([1,2,'n','njsnnln']).
input([7,8,'z','gzczzwdzkkzz']).
input([2,8,'b','bbbwjfbh']).
input([6,8,'r','rrrrbrrbr']).
input([2,5,'k','lkkkkl']).
input([2,3,'c','swcgjcm']).
input([2,10,'t','ttttttttttt']).
input([12,13,'l','lllllxllllllqhl']).
input([2,9,'l','qtqxdpqqlwhqwlr']).
input([1,5,'q','qqxrn']).
input([10,11,'k','kkkkkkkkkckk']).
input([1,2,'f','ffff']).
input([3,4,'r','rrxr']).
input([8,9,'p','lppppxpsp']).
input([2,5,'s','ssstchlrds']).
input([11,15,'m','mmmmmmmmmmmmmmmmm']).
input([14,17,'k','kkkkkkkkkkgkkkktbkk']).
input([1,2,'x','xlxx']).
input([9,10,'w','wwcwptczwzzd']).
input([1,3,'c','ccgcccccccccccccc']).
input([4,5,'h','nhhhvh']).
input([8,16,'l','hlllfllllmltlhlldl']).
input([4,5,'w','wgwfw']).
input([6,15,'p','pjpbfrmxqgkxkbqhj']).
input([12,17,'l','llmtllnlllllllllnns']).
input([8,15,'n','zjnxzndnznklxzjlx']).
input([6,9,'r','wpsmstnkgtrmng']).
input([3,7,'s','csvhxhsgvrsrn']).
input([10,15,'h','hchhhdhkhghlhgsh']).
input([2,9,'c','mzbmtccktc']).
input([3,4,'x','xlzvxg']).
input([12,14,'k','zmkskknwkkkmkkwkgkkk']).
input([4,9,'r','vqrrrrdzpl']).
input([3,4,'g','ggvbxg']).
input([5,8,'q','xtrqrmqq']).
input([16,18,'l','zllllllllllllllwlnll']).
input([6,7,'s','zsqszss']).
input([3,4,'g','wghgpg']).
input([1,6,'z','hzzzzrz']).
input([3,8,'h','hthfqtccnq']).
input([15,18,'p','ppppppcpppppppnppppp']).
input([3,4,'l','qplkdmjntlghjlpxlq']).
input([10,12,'q','xzqkxdvgrqxqqzzxgjj']).
input([6,9,'q','qqqvsvqqxq']).
input([12,13,'g','shgcnjlgvcgqg']).
input([5,10,'l','llklplllmlsl']).
input([3,12,'l','vllqfzwnsqslpnvrbkh']).
input([14,16,'g','gjggggggggggggbzcggg']).
input([5,11,'m','ssmsmbnspmm']).
input([11,13,'v','mkqvvvvvmcvvz']).
input([2,3,'k','mkkchtzqsvkbclgxn']).
input([4,7,'r','rphrrnrrqwknrktrgsg']).
input([6,10,'z','vpjhzzzkqzjl']).
input([16,18,'c','ccccccccccccccchccc']).
input([1,10,'v','qvvvvzvvvvvv']).
input([5,7,'j','jjrjjjj']).
input([14,16,'l','zlgdrlqllgpllfhh']).
input([3,6,'l','llmllll']).
input([3,4,'l','smdl']).
input([4,11,'h','kgqhcpvrbldrhbq']).
input([1,15,'j','ljjjjjjjjjjjjjjj']).
input([7,14,'c','ccccccccccccccc']).
input([2,10,'v','vzvjvvvvvvvvv']).
input([4,9,'p','flbpmqmhkpt']).
input([10,12,'q','rtdrqmpcsqrhqqchqczw']).
input([16,19,'w','vlwxgtmjwrzvqgdwbdw']).
input([8,15,'c','gkcccslctcmszhc']).
input([3,7,'f','hhffhbbtbwzw']).
input([4,9,'s','msbsxssds']).
input([13,15,'p','pppppppppcpppxldp']).
input([6,7,'m','mmmmmqmm']).
input([11,12,'m','mxmmzwmmmdqpmp']).
input([7,12,'l','gncmgzxlqcllqgt']).
input([12,14,'t','tttttttttttdtt']).
input([2,6,'f','ffffffbrfffp']).
input([14,17,'h','hhdhpphhhhhhkhhxqph']).
input([7,9,'x','xxxxxxxxqxxxxxx']).
input([5,18,'j','vlwgjljtljtrdbxjnjwm']).
input([5,7,'n','jmncnsndnbwx']).
input([8,9,'r','rrrrrrrrr']).
input([11,17,'j','jjjjjjjjjjjjjjpjr']).
input([5,6,'x','xxxxjt']).
input([13,15,'l','nshmnjgzhmjdzvl']).
input([9,10,'r','wmsvzxsrqnnhfr']).
input([8,11,'k','kkkxxrkpktg']).
input([1,7,'r','rrrrrrrfrrrjwrd']).
input([5,7,'t','rztvtvplbrk']).
input([2,7,'w','wwwwwwsw']).
input([1,2,'g','sgggk']).
input([12,13,'j','jjjjjwjjjjvvjjjrjs']).
input([1,2,'c','cccccc']).
input([3,5,'g','khgzr']).
input([9,16,'b','bbbbbbcbsbbbbbbb']).
input([12,13,'z','zzzzzzzzzszkz']).
input([4,5,'r','rkrrrr']).
input([1,2,'t','tgbqtddbmq']).
input([1,2,'w','wkwwwww']).
input([14,15,'q','qqdqqqqqqqqhqnb']).
input([6,7,'r','rrrrrdmrr']).
input([8,9,'j','jjjjjjjqhjjjjj']).
input([3,6,'t','gwmlntffstzllvs']).
input([6,8,'h','hhhhnhhhqh']).
input([9,11,'w','cwcwwwwwgxwwbw']).
input([5,9,'w','wwwwcwwww']).
input([8,12,'k','snjmkkhrgkkzkkpskk']).
input([3,6,'q','lvqjqlq']).
input([3,4,'z','zzzn']).
input([9,12,'t','dvmvhttxtmzhrr']).
input([3,7,'k','kkkkkkskkkkkk']).
input([6,15,'v','vqvvvdvvvvbvvvvvvvvv']).
input([3,4,'z','jzzzzzdk']).
input([8,12,'b','bbbbbbbbbbbs']).
input([3,9,'m','nvhwmwgmmqkbmmmzb']).
input([8,10,'r','npwjcgwrwcrx']).
input([1,5,'r','rxdrr']).
input([6,9,'p','ppppppsbkmppkp']).
input([1,4,'j','jjjqjjjz']).
input([6,7,'b','rblbbbbbbp']).
input([5,9,'t','tttttttttf']).
input([8,9,'c','czcccccccc']).
input([13,14,'j','jjjbjjtbjjjjjj']).
input([3,8,'p','pwppzqvp']).
input([3,12,'m','mmzmmmmmmmmmmm']).
input([3,9,'d','ddjddddddqddd']).
input([3,4,'q','qqfq']).
input([6,14,'m','mmmmmbmmmmwmmlmmmm']).
input([3,4,'c','glgzc']).
input([6,7,'t','ttttttt']).
input([1,4,'s','sssbs']).
input([5,8,'r','drrkrrrzrrrr']).
input([10,12,'q','rvqfqqkllqqqlfrq']).
input([11,13,'s','szsssssssssssss']).
input([8,11,'t','tttttttsttvt']).
input([11,15,'j','zjjjjjjjjjjjjjjjjj']).
input([2,4,'s','dvfs']).
input([3,4,'q','zhpq']).
input([10,11,'c','cccccccccckc']).
input([5,11,'h','pnrjhtdlkzvhh']).
input([5,9,'l','nlllxgnrlllllllmq']).
input([3,4,'f','gfff']).
input([8,9,'g','grgggggbg']).
input([3,4,'j','pfwjhh']).
input([2,5,'l','jlfjr']).
input([2,4,'l','lblv']).
input([3,10,'q','qqvzhnqqhqvqq']).
input([11,15,'t','tfttttttktwttts']).
input([12,14,'b','gqptrzwclbdbfqd']).
input([1,4,'r','crrprr']).
input([5,13,'v','qvdvvvdnrqmrqp']).
input([9,12,'r','rwrrlsrrsrrjgdnrrr']).
input([4,6,'c','ccldccnp']).
input([16,17,'q','qqqqqpqqqqlqqqqmlq']).
input([2,8,'w','wwwwwwwhwmwws']).
input([3,6,'m','dmmbmmdmkxm']).
input([6,13,'t','xflrtblvcvfxnlf']).
input([2,6,'m','pmnsmm']).
input([13,15,'k','kstfvnkkgfvvkbk']).
input([4,10,'w','jqwcwlcwcwvqbfzfzfm']).
input([1,5,'d','ddndbmjxhfqqn']).
input([13,16,'p','pzvbszhqtpklpkpdw']).
input([2,4,'t','thttwmxjsbtp']).
input([8,10,'s','zbsvjcssfmf']).
input([3,5,'l','lltlwlllll']).
input([12,14,'g','hgfvvfpnrvpfggnss']).
input([3,13,'q','cjmbvgxchmqdqcvc']).
input([12,16,'j','cjjjjjjjjjjqjjjjjj']).
input([1,5,'m','kqrgm']).
input([11,14,'x','xcjpwbrrffxkfxh']).
input([12,14,'c','kgfnccxqczkcjkcc']).
input([3,4,'f','sfftf']).
input([1,3,'f','ffdz']).
input([12,14,'t','xftfxmkttdsttg']).
input([4,9,'f','ffhcgfffffff']).
input([9,10,'b','zjlbbsbzbx']).
input([9,14,'m','hhxmlmmmzmmtmm']).
input([3,5,'t','tkcpzjwr']).
input([6,9,'k','wkfdwflgrntrknsr']).
input([1,4,'l','gfml']).
input([9,10,'z','zzzzzzzzzrzzzz']).
input([9,11,'h','hhhhhhhhhhzhh']).
input([1,9,'k','kkkkkkkkzkkkkkkk']).
input([2,7,'h','sswmmkhkvhw']).
input([2,5,'m','pmbnnmzrkk']).
input([9,12,'f','xhpfbfdffkfw']).
input([3,4,'g','gfwg']).
input([11,12,'n','nnnnnnnnnnnpnnnxn']).
input([5,6,'d','dddddgddd']).
input([7,9,'j','cbjgnjqjgj']).
input([9,14,'r','rrrrrrrhrrrrrzbrr']).
input([4,5,'p','prphk']).
input([2,4,'d','dpdd']).
input([5,15,'p','zjsppzhqqgqspcppqpps']).
input([2,7,'r','rrrrrrfwrr']).
input([1,3,'h','hhqh']).
input([14,16,'g','zgvdgspkjrrvcgdlxg']).
input([4,6,'c','psgqccccvc']).
input([9,14,'q','qdqjqmttdtcqggqpqn']).
input([13,18,'f','ffffffffffffgffffff']).
input([8,9,'g','gggggggggggg']).
input([11,12,'x','xxxxxxxxxxxr']).
input([2,17,'c','cxcccfchcccccccbbcm']).
input([7,11,'b','nwbrzndvrfxwt']).
input([3,4,'x','xhwxxxv']).
input([16,17,'r','rzrrnrrrvxrrzrrrrrr']).
input([2,3,'f','zcvgbmxvwp']).
input([5,6,'b','fwbbbf']).
input([6,10,'m','mmmmmpmmmw']).
input([2,4,'n','bnnvndbpvzj']).
input([3,4,'t','dftfhdngqp']).
input([1,2,'v','vtvvvvvvvvv']).
input([2,3,'v','vgvv']).
input([9,10,'s','tsvsshsssgssssmsksss']).
input([6,7,'t','ttttttxt']).
input([3,4,'c','jcrc']).
input([5,8,'l','ztlmjljlb']).
input([4,5,'w','bwwwww']).
input([11,14,'r','rrrbrrrrrrnrrrs']).
input([10,16,'z','zzzzznzzzwzzzzzzzz']).
input([7,13,'m','mmmmmmfmmmmmmmmmmmmm']).
input([15,19,'w','fflzcwftmcswcwwnwts']).
input([10,19,'b','bjbbbbbbmwbbbbbbbbtb']).
input([14,16,'x','xxxxpxxpxxqxdqxxxx']).
input([8,13,'r','rkzrjbxrgwkhnb']).
input([5,18,'r','rrrzfkrrrrrrrrtrrnrr']).
input([4,5,'b','bbbfzb']).
input([6,10,'q','qnscxqqfqb']).
input([8,13,'w','wwwwwwwfwwwwwwwwww']).
input([10,11,'n','scvnsnpgnjnmdpnwct']).
input([7,11,'p','pjpppppdqpjpfppsptp']).
input([7,9,'n','jfsvclhfm']).
input([3,8,'h','whsggqscd']).
input([2,12,'r','mrmpxhrqsdmqpjshvck']).
input([2,4,'g','gdgggg']).
input([7,12,'s','ssssssssgsss']).
input([7,11,'l','dlklllnjlslbl']).
input([5,11,'k','kkkkkkkkkkkkkkk']).
input([6,9,'g','dhtvcgmfrjhk']).
input([4,5,'m','lmmmhmsmmmmmcmmmmzmm']).
input([11,13,'t','zgtnkjzmtkttmtkc']).
input([6,7,'b','bbbbbbv']).
input([3,4,'q','qqcq']).
input([12,16,'z','zzzszjzszzczmxtzzcl']).
input([2,5,'w','wwfhp']).
input([1,2,'d','gddkd']).
input([5,12,'f','fwqgbvrcfmwb']).
input([2,5,'w','bnxcw']).
input([3,15,'t','ncwftppphsxvztttjs']).
input([7,10,'p','ppnsppkcppsp']).
input([5,6,'v','vvrdvv']).
input([5,6,'z','hczwbzz']).
input([3,12,'p','gcphfgmzfkflspmxg']).
input([14,19,'m','jmfmfjpvbmfmmrdkdnzp']).
input([6,7,'p','pdwzppppp']).
input([4,7,'b','bbbnbbqbb']).
input([7,8,'r','frrrrrxxr']).
input([8,18,'b','jbphpzgvnppwhkxfzs']).
input([1,5,'c','pvhcc']).
input([4,8,'z','fzznzjzztstzxrz']).
input([5,10,'v','jvvwvvvlvlvqc']).
input([7,14,'p','svgrzfpxkdpbhph']).
input([5,7,'n','nncmvkn']).
input([11,12,'r','rrlrbrrrvrrr']).
input([1,5,'r','vtngrndhqf']).
input([2,4,'k','knjp']).
input([11,14,'h','hhghhhhhhhxhhwhhh']).
input([16,18,'r','rrrrrrrrrrrrrrrpnb']).
input([10,14,'d','dpddbvdtdmxfdddd']).
input([2,4,'t','cztt']).
input([5,6,'r','rzrprd']).
input([2,5,'n','ngwdngc']).
input([1,6,'q','qqqzzwwqqqkqqq']).
input([7,8,'l','lllzllpxl']).
input([1,4,'b','kmltzzjzbppgwq']).
input([1,4,'t','ttttb']).
input([3,4,'p','dkxpcph']).
input([7,15,'z','zzzzzzhzzzzzzzzzz']).
input([4,7,'c','cdljfccm']).
input([3,8,'p','hbpxhlmc']).
input([4,5,'w','wwwlw']).
input([14,15,'b','lbqbbbkgbbwfbdb']).
input([6,10,'j','jtjjvpwwthwcsj']).
input([5,8,'t','ltvtttbtqxtzq']).
input([12,13,'t','ttttttttjttztxt']).
input([16,18,'p','ppppppppppppppxpxbpp']).
input([4,7,'n','nnnrnnnnt']).
input([1,2,'r','rfrr']).
input([5,6,'g','ggggvggg']).
input([3,4,'s','ssbw']).
input([3,4,'l','ldll']).
input([8,10,'m','mmmmvmmcjkmg']).
input([10,18,'w','wwvwwvwwhwwjwwwlwxcm']).
input([1,2,'x','cxxxxxxxxxxxxx']).
input([1,5,'b','bbbbkbbb']).
input([12,14,'z','zwqzrrzzvqqzzszrx']).
input([1,5,'z','lzzfzzzfz']).
input([16,17,'t','ftgstrgptwmptxrzt']).
input([9,10,'b','bbbbbbbzbbbb']).
input([8,14,'w','wwwwwwwjwwwzwzww']).
input([3,4,'h','qhnh']).
input([2,12,'d','dnddddkddddzdxdddd']).
input([5,17,'x','xxxxxxxxxxxxxxxxx']).
input([9,10,'h','hhhhtqhhhrh']).
input([6,7,'p','pfmppppp']).
input([5,8,'v','vbvvvvvs']).
input([4,5,'h','qhfhqcb']).
input([3,12,'d','dlddlhhwvcrdrxwpt']).
input([2,3,'n','nnwnp']).
input([4,8,'g','ggggjgfgzgdglgg']).
input([4,9,'h','vrghsphxhxzsxw']).
input([12,18,'z','qrzzzfwdcwnzdzkckz']).
input([6,8,'v','zvmlqwwh']).
input([10,14,'p','pppxwpndfpwppdpptmpp']).
input([12,15,'q','qqnqkqkqjgrcqfq']).
input([2,4,'n','pnszjnnn']).
input([2,3,'c','zkctcfc']).
input([17,20,'l','lvjlcclllslzllllwgll']).
input([16,17,'k','dfgskkfkkkfjhfvfks']).
input([1,3,'t','tjttltt']).
input([2,3,'b','bbzbb']).
input([8,15,'t','dtttttsttlttttzlttj']).
input([13,14,'v','vvkvvjvgwvvvkvf']).
input([7,8,'v','tvvvvvvhv']).
input([3,10,'d','bxktdrtddtdtsh']).
input([4,12,'j','npwxjjjjbjkq']).
input([1,4,'l','tlllll']).
input([12,13,'b','lbhpxbbbvbbbqbbbsbb']).
input([9,15,'v','vqhsggmpvmqtbzzlq']).
input([12,14,'f','ffhfjfffqfxqff']).
input([15,16,'m','jtnsjwpggbpxlhqmk']).
input([2,4,'n','xptncjsstcl']).
input([5,8,'q','dmwklqjqnzb']).
input([3,4,'c','vcgl']).
input([1,6,'h','hhhhhh']).
input([8,9,'x','ckblstcdx']).
input([5,7,'w','vwphwwmwwwww']).
input([2,4,'x','kxxxdh']).
input([10,11,'m','kmmvmmmfmksmj']).
input([4,7,'v','zvrvvvdvvv']).
input([1,8,'p','npxbwqpxbjrnrv']).
input([5,11,'t','jfkwttkstrxlgts']).
input([1,2,'g','ggggg']).
input([5,7,'p','tpppppr']).
input([15,17,'v','vvvvvvvvvvvvvvvvvvvv']).
input([17,19,'w','dwjwjznczwgfmkmhdtw']).
input([10,13,'f','fffffbqfffffffffff']).
input([4,14,'g','ggggggggggggggg']).
input([2,3,'d','bdkfd']).
input([7,8,'x','xxxxxxxx']).
input([6,9,'h','hmshdhvvhkhbhcshs']).
input([14,15,'g','gggggggggggggghg']).
input([2,16,'q','qqsxqqqdgqqghqqk']).
input([3,17,'p','ppbppprppppppppphppp']).
input([8,18,'v','vczfvqcvvcspndvxwjdv']).
input([1,3,'d','fdddd']).
input([9,11,'j','gfjjnjsdnhb']).
input([8,10,'s','hkhshttssl']).
input([5,10,'f','ffsffffffqxfff']).
input([7,10,'w','wwlwwckwwf']).
input([4,8,'x','blxxmtbgnblfgnfwz']).
input([4,5,'p','rlpkprppp']).
input([13,14,'s','ssssssssssssswss']).
input([4,8,'h','hhhdhmhhhjhlhh']).
input([6,7,'h','chhhhhfhzqhdhhh']).
input([15,17,'m','msvrmwzkzvmmgrmmpm']).
input([4,6,'x','qgtwwxhgsxxmklgmn']).
input([4,7,'p','rpzkdpp']).
input([3,4,'v','vvvhvjv']).
input([16,18,'p','pppppppppppppppppmp']).
input([15,17,'k','kpkkkkkhqkkkkklktk']).
input([5,7,'s','ssbxxsk']).
input([2,4,'l','cwllll']).
input([6,9,'v','cvvrrkvrvsdvfwcv']).
input([1,7,'w','qwwwwslwwwwwwwwrww']).
input([2,12,'c','clcccccccccccccc']).
input([5,10,'m','ftcmrpmvrzc']).
input([7,11,'w','wwwwwwwwwwtwwwww']).
input([2,3,'n','jngdlvgcvtkmn']).
input([1,8,'v','hvvvvvvvvv']).
input([3,17,'p','jrpvltxlcqgpfxwsj']).
input([1,5,'k','kkkkfkk']).
input([1,10,'c','cccccccccfc']).
input([13,19,'f','flfffffxfvffffprfmcb']).
input([3,6,'g','htglsbvrzcghjmd']).
input([9,11,'h','wrwghhhhnzhxl']).
input([5,12,'z','zzkzzhnjpmkvzzzw']).
input([7,11,'w','qrwcwwstwddw']).
input([15,19,'m','mmmmmmmmmmmmmmmmmmmm']).
input([15,16,'m','mmmmmmmmmmmmmmhmm']).
input([12,16,'x','xxxxxcxxxxxlxxxxxxx']).
input([5,10,'l','qwfqlllgsdjrlspll']).
input([3,4,'f','hffmfffg']).
input([6,7,'l','lwlllbllnl']).
input([11,20,'t','tttkrtlpttwftmwttttt']).
input([11,12,'d','ddbdddddddpktdd']).
input([4,11,'w','sxkmkwdwwnlwxmdvfx']).
input([4,5,'k','kkzkpk']).
input([13,20,'n','nnnnnntnnnnnbnnnbnnn']).
input([5,7,'c','ccccwcc']).
input([1,6,'h','cckkhhdhhwmhhmzchhwx']).
input([1,15,'b','hbbbbbbbbhbbhbbbbnbb']).
input([1,2,'w','mwwww']).
input([1,2,'f','sfzgwtf']).
input([3,4,'s','sssj']).
input([1,3,'w','xwww']).
input([1,16,'p','ppppppppdppppppp']).
input([1,6,'c','ccxmccccc']).
input([4,8,'b','rtpbcfbr']).
input([9,10,'s','sszssstshss']).
input([15,16,'x','xxxtxxxxxxxmxxxzx']).
input([9,15,'k','kkkkkkkkkkgrkkkkk']).
input([11,13,'x','xtxxxxxxxxrxkxx']).
input([1,5,'f','rffflfffnf']).
input([14,16,'n','nnxnnnnnnnnnbnzbnnn']).
input([3,6,'d','ddddddndbdfdhd']).
input([14,15,'q','sbqqhvqqqvqgxfq']).
input([5,6,'b','jglbfjb']).
input([1,10,'l','llllllcllsll']).
input([3,5,'z','lwzzz']).
input([5,12,'k','kkkkmkkkkkkkkkkl']).
input([8,12,'v','vvtsvfvnzvhpm']).
input([5,7,'l','llllllll']).
input([4,7,'f','nqfffkbdf']).
input([4,8,'j','jjjljkhj']).
input([9,15,'h','vgzpgfhfhmwdhbqc']).
input([1,5,'p','ptpsjqpnp']).
input([5,8,'q','qbqqwqnq']).
input([5,7,'w','wwswwxsb']).
input([3,6,'h','nnhrnhkmxqkt']).
input([1,3,'w','jwwww']).
input([2,14,'x','cxxxxdxxxxxxxbxx']).
input([12,14,'x','xxxfxxxxqxxrxt']).
input([4,9,'f','fffkffbsfkxv']).
input([12,13,'m','mmmmmmmmmmmwm']).
input([6,10,'p','ppppphpppxppp']).
input([9,12,'v','vsvvvvkmjvvvn']).
input([3,12,'r','shngvhbmjrpr']).
input([12,13,'w','wqwcwxclwwwfw']).
input([4,5,'r','nnrrdz']).
input([4,19,'c','vbcpwzvxssccqkqgmxvj']).
input([1,6,'g','tglxhggng']).
input([9,10,'z','lvzhvtglzf']).
input([10,16,'f','gddxfftggfbmxwts']).
input([4,12,'k','kkkklkkkkkkpkkk']).
input([7,11,'m','mmmmmmmmmmtm']).
input([2,10,'z','vkfpjrrvlwlbjwk']).
input([3,7,'w','dtdzwjqgxdwjhchwwd']).
input([13,14,'v','vvvvvvvvvvvvvvvv']).
input([11,12,'c','cjccccqccccc']).
input([14,15,'h','hzhrhkhfthrhxht']).
input([3,5,'v','dtwvvvvvcvvvrvsvvv']).
input([10,14,'q','qhqqkqcqqqqqlfqgsqq']).
input([3,14,'f','ffvffffffffzffffff']).
input([1,12,'x','xxtxjxzxxxxxlxxxxxxx']).
input([2,4,'c','pgpc']).
input([1,4,'r','fdrr']).
input([5,7,'r','rrrrrrt']).
input([10,11,'d','drdddddddmddddpd']).
input([2,5,'f','gfrlctftzr']).
input([10,13,'z','nrzjjrzjzzplzmzzbn']).
input([8,10,'c','cccccccgbc']).
input([5,8,'g','fgggcndwgggbjnfgb']).
input([6,9,'d','ddddghdgbddm']).
input([3,7,'j','ftjjjvjqcp']).
input([5,6,'s','sqvfstz']).
input([5,18,'k','kkkwkkkkkkbkkkkkkkbk']).
input([3,6,'f','djffffkff']).
input([4,6,'p','pqppppr']).
input([5,9,'h','hhkhjhmgcqvfhqvhn']).
input([8,12,'t','tttttttvttttt']).
input([14,15,'z','pzrzhjqmtbcnzdzr']).
input([1,17,'s','ssssssssssssswsss']).
input([1,4,'s','ssqh']).
input([1,5,'r','rrrrrrr']).
input([17,18,'h','hhhhhrhcxhhhhhhhhb']).
input([7,9,'t','dttttjmtv']).
input([1,3,'c','mcccp']).
input([4,5,'x','xprbxql']).
input([1,5,'q','cqqqqqq']).
input([3,4,'g','ggggw']).
input([1,7,'f','ffffffnf']).
input([7,9,'t','ttttttttttt']).
input([11,15,'m','mmlmfmmmmmmmmmmqm']).
input([4,5,'n','npnnnn']).
input([4,5,'b','zvbbvbjhlkf']).
input([11,16,'c','gnqmcvtzwpcbvncwcc']).
input([12,18,'q','qbqkwqqvqwqqnljsqpqt']).
input([6,10,'r','wcrtdrlkgjr']).
input([16,17,'p','gppppppppwvlgpptp']).
input([1,13,'g','gqghbwqqzwwdk']).
input([1,6,'l','rlllll']).
input([3,7,'j','pdjjtcqwbqtpfkjbwgq']).
input([7,17,'z','zzhsnjrhrzzfrqszdhdg']).
input([6,7,'n','xnvnhnrn']).
input([6,7,'r','rrrrrrzr']).
input([2,3,'c','ccmcccc']).
input([2,3,'v','vvdv']).
input([3,9,'f','mlfffshbfdff']).
input([11,13,'v','dfvkltvjvvvvx']).
input([12,13,'c','mqrccccbccbgcccccvc']).
input([9,13,'w','wwwwwwwwwwwwcwtww']).
input([6,8,'d','pdvgddtmvwdkvdtzf']).
input([1,9,'s','hsssssssssdsls']).
input([1,5,'c','zbsslcd']).
input([1,4,'p','bpppppppppp']).
input([13,16,'s','sssxslsscssbqsspcs']).
input([1,10,'p','pskwpppzpppppks']).
input([3,5,'c','ccppccmcc']).
input([10,11,'b','rhbbbbbbbzbb']).
input([2,3,'d','ndhjhd']).
input([3,4,'s','sscs']).
input([5,6,'d','dtwwnt']).
input([4,5,'d','dddddddd']).
input([5,9,'z','zztzvzzzz']).
input([2,6,'v','vpqdll']).
input([13,14,'d','nxkmbkkpxkcdld']).
input([1,3,'s','ssss']).
input([8,14,'z','zzzzzzzzzzzzzbz']).
input([16,17,'f','fffnffffffftbzffpkf']).
input([3,4,'m','mtcm']).
input([3,4,'r','mrdrd']).
input([11,13,'k','ljkmhdkkkcpjzlmkkzkk']).
input([2,3,'d','tdqnxpd']).
input([3,7,'h','mrvdlthxchpvwvssqpk']).
input([13,17,'j','jjfjjvjjjjjzjsjjksxr']).
input([1,4,'n','rnnx']).
input([7,10,'m','mmmmzmxfmm']).
input([1,6,'r','lrrvrrrrm']).
input([4,18,'r','rrrdrrrrrrrrrkblrr']).
input([6,7,'k','kkkkkkl']).
input([4,6,'v','vmnfvvvvmcmlh']).
input([6,9,'g','jgcgggkbbmgbs']).
input([7,8,'t','ttcfwtgjtcttv']).
input([3,4,'j','tjjj']).
